/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author user
 */
public class addMhs_view extends javax.swing.JFrame {

    /**
     * Creates new form addMhs_view
     */
    public addMhs_view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfNamaDataDMhs = new javax.swing.JTextField();
        tfNimDataDMhs = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbLakiDataDMhs = new javax.swing.JRadioButton();
        rbPerempuanDataDMhs = new javax.swing.JRadioButton();
        btnAddDataDMhs = new javax.swing.JButton();
        btnEditDataDMhs = new javax.swing.JButton();
        btnRemoveDataDMhs = new javax.swing.JButton();
        btnResetDataDMhs = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDataDMhs = new javax.swing.JTable();
        tfSearchDataDMhs = new javax.swing.JTextField();
        btnSearchDataDMhs = new javax.swing.JButton();
        cbJurusanDataDMhs = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Data Mahasiswa");

        jLabel2.setText("Nama");

        jLabel3.setText("NIM");

        jLabel4.setText("Jurusan");

        jLabel5.setText("Jenis kelamin");

        rbLakiDataDMhs.setText("Laki-laki");

        rbPerempuanDataDMhs.setText("Perempuan");

        btnAddDataDMhs.setText("Add");
        btnAddDataDMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDataDMhsActionPerformed(evt);
            }
        });

        btnEditDataDMhs.setText("Edit");
        btnEditDataDMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDataDMhsActionPerformed(evt);
            }
        });

        btnRemoveDataDMhs.setText("Remove");

        btnResetDataDMhs.setText("Reset");
        btnResetDataDMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDataDMhsActionPerformed(evt);
            }
        });

        tbDataDMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama", "NIM", "Jurusan"
            }
        ));
        jScrollPane1.setViewportView(tbDataDMhs);

        tfSearchDataDMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchDataDMhsActionPerformed(evt);
            }
        });

        btnSearchDataDMhs.setText("Search");

        cbJurusanDataDMhs.setEditable(true);
        cbJurusanDataDMhs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Informatika", "S1 Teknologi Infromasi" }));
        cbJurusanDataDMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJurusanDataDMhsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNamaDataDMhs)
                                    .addComponent(tfNimDataDMhs)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbLakiDataDMhs)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbPerempuanDataDMhs)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cbJurusanDataDMhs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddDataDMhs)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditDataDMhs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoveDataDMhs)
                                .addGap(18, 18, 18)
                                .addComponent(btnResetDataDMhs)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(43, 43, 43)
                        .addComponent(tfSearchDataDMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchDataDMhs)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(264, 264, 264))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNamaDataDMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNimDataDMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbJurusanDataDMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbLakiDataDMhs)
                    .addComponent(rbPerempuanDataDMhs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDataDMhs)
                    .addComponent(btnEditDataDMhs)
                    .addComponent(btnRemoveDataDMhs)
                    .addComponent(btnResetDataDMhs)
                    .addComponent(tfSearchDataDMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchDataDMhs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDataDMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDataDMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddDataDMhsActionPerformed

    private void btnEditDataDMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDataDMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditDataDMhsActionPerformed

    private void btnResetDataDMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDataDMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetDataDMhsActionPerformed

    private void tfSearchDataDMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchDataDMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchDataDMhsActionPerformed

    private void cbJurusanDataDMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJurusanDataDMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJurusanDataDMhsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addMhs_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addMhs_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addMhs_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addMhs_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addMhs_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDataDMhs;
    private javax.swing.JButton btnEditDataDMhs;
    private javax.swing.JButton btnRemoveDataDMhs;
    private javax.swing.JButton btnResetDataDMhs;
    private javax.swing.JButton btnSearchDataDMhs;
    private javax.swing.JComboBox<String> cbJurusanDataDMhs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbLakiDataDMhs;
    private javax.swing.JRadioButton rbPerempuanDataDMhs;
    private javax.swing.JTable tbDataDMhs;
    private javax.swing.JTextField tfNamaDataDMhs;
    private javax.swing.JTextField tfNimDataDMhs;
    private javax.swing.JTextField tfSearchDataDMhs;
    // End of variables declaration//GEN-END:variables
}
