/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author user
 */
public class DosenKelasTA extends javax.swing.JFrame {

    /**
     * Creates new form DosenKelasTA
     */
    public DosenKelasTA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlDaftarNamaKelasTA = new javax.swing.JLabel();
        jlDaftarDosenTA = new javax.swing.JLabel();
        tfDaftarNamaKelasTA = new javax.swing.JTextField();
        jfDaftarKK = new javax.swing.JLabel();
        btnAddDaftarKelasTA = new javax.swing.JButton();
        btnEditDaftarKelasTA = new javax.swing.JButton();
        btnRemoveDaftarKelasTA = new javax.swing.JButton();
        btnResetDaftarKelasTA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDaftarKelasTA = new javax.swing.JTable();
        tfSearchDaftarKelasTA = new javax.swing.JTextField();
        btnSearchDaftarKelasTA = new javax.swing.JButton();
        cbDaftarKK = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Daftar Kelas TA");

        jlDaftarNamaKelasTA.setText("Nama kelas");

        jlDaftarDosenTA.setText("Dosen");

        jfDaftarKK.setText("KK");

        btnAddDaftarKelasTA.setText("Add");
        btnAddDaftarKelasTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDaftarKelasTAActionPerformed(evt);
            }
        });

        btnEditDaftarKelasTA.setText("Edit");
        btnEditDaftarKelasTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDaftarKelasTAActionPerformed(evt);
            }
        });

        btnRemoveDaftarKelasTA.setText("Remove");

        btnResetDaftarKelasTA.setText("Reset");
        btnResetDaftarKelasTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDaftarKelasTAActionPerformed(evt);
            }
        });

        tbDaftarKelasTA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Nama kelas", "Kode kelas"
            }
        ));
        jScrollPane1.setViewportView(tbDaftarKelasTA);

        tfSearchDaftarKelasTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchDaftarKelasTAActionPerformed(evt);
            }
        });

        btnSearchDaftarKelasTA.setText("Search");

        cbDaftarKK.setEditable(true);
        cbDaftarKK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIDE", "ICM", "TELE", "MCE" }));
        cbDaftarKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDaftarKKActionPerformed(evt);
            }
        });

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SPT", "ANI", "MYA", "ANAS" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlDaftarNamaKelasTA)
                                    .addComponent(jlDaftarDosenTA)
                                    .addComponent(jfDaftarKK))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDaftarNamaKelasTA)
                                    .addComponent(cbDaftarKK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddDaftarKelasTA)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditDaftarKelasTA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoveDaftarKelasTA)
                                .addGap(18, 18, 18)
                                .addComponent(btnResetDaftarKelasTA)
                                .addGap(0, 53, Short.MAX_VALUE)))
                        .addGap(43, 43, 43)
                        .addComponent(tfSearchDaftarKelasTA, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchDaftarKelasTA)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(317, 317, 317))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDaftarNamaKelasTA)
                    .addComponent(tfDaftarNamaKelasTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDaftarDosenTA)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfDaftarKK)
                    .addComponent(cbDaftarKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDaftarKelasTA)
                    .addComponent(btnEditDaftarKelasTA)
                    .addComponent(btnRemoveDaftarKelasTA)
                    .addComponent(btnResetDaftarKelasTA)
                    .addComponent(tfSearchDaftarKelasTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchDaftarKelasTA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDaftarKelasTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDaftarKelasTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddDaftarKelasTAActionPerformed

    private void btnEditDaftarKelasTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDaftarKelasTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditDaftarKelasTAActionPerformed

    private void btnResetDaftarKelasTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDaftarKelasTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetDaftarKelasTAActionPerformed

    private void tfSearchDaftarKelasTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchDaftarKelasTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchDaftarKelasTAActionPerformed

    private void cbDaftarKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDaftarKKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDaftarKKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DosenKelasTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DosenKelasTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DosenKelasTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DosenKelasTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DosenKelasTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDaftarKelasTA;
    private javax.swing.JButton btnEditDaftarKelasTA;
    private javax.swing.JButton btnRemoveDaftarKelasTA;
    private javax.swing.JButton btnResetDaftarKelasTA;
    private javax.swing.JButton btnSearchDaftarKelasTA;
    private javax.swing.JComboBox<String> cbDaftarKK;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jfDaftarKK;
    private javax.swing.JLabel jlDaftarDosenTA;
    private javax.swing.JLabel jlDaftarNamaKelasTA;
    private javax.swing.JTable tbDaftarKelasTA;
    private javax.swing.JTextField tfDaftarNamaKelasTA;
    private javax.swing.JTextField tfSearchDaftarKelasTA;
    // End of variables declaration//GEN-END:variables
}
