/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;

/**
 *
 * @author user
 */
public class PilihanDosen_view extends javax.swing.JFrame {

    /**
     * Creates new form PilihanDosen_view
     */
    public PilihanDosen_view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDosenPilihKelasTA = new javax.swing.JButton();
        btnApprovalDosenKelasTA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDosenPilihKelasTA.setText("KelasTA");

        btnApprovalDosenKelasTA.setText("Approval");
        btnApprovalDosenKelasTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovalDosenKelasTAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnApprovalDosenKelasTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDosenPilihKelasTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(btnDosenPilihKelasTA)
                .addGap(28, 28, 28)
                .addComponent(btnApprovalDosenKelasTA)
                .addGap(108, 108, 108))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApprovalDosenKelasTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovalDosenKelasTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApprovalDosenKelasTAActionPerformed
     
    public JButton getBtnApprovalDosenKelasTA() {
        return btnApprovalDosenKelasTA;
    }

    public JButton getBtnDosenPilihKelasTA() {
        return btnDosenPilihKelasTA;
    }

    
//    public void addMouseAdapter(MouseAdapter x){
//        btnDosenPilihKelasTA.addMouseListener(x);
//        btnApprovalDosenKelasTA.addMouseListener(x);
//    }
       public void setBtnApprovalDosenKelasTA(ActionListener act){
        btnApprovalDosenKelasTA.addActionListener(act);
    }
    
    public void setBtnDosenPilihKelasTA(ActionListener act){
        btnDosenPilihKelasTA.addActionListener(act);
//        
    }
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprovalDosenKelasTA;
    private javax.swing.JButton btnDosenPilihKelasTA;
    // End of variables declaration//GEN-END:variables
}
